#!/usr/bin/env python3
"""Builds src/js/05-icons.js from the Lucide SVG files in this directory.
Run after adding an icon: python3 src/icons/make-sprite.py
Standard library only. Icons: https://lucide.dev, ISC license (LICENSE next to it)."""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "js", "05-icons.js")

symbols = []
for name in sorted(os.listdir(HERE)):
    if not name.endswith(".svg"):
        continue
    with open(os.path.join(HERE, name), encoding="utf-8") as f:
        svg = f.read()
    inner = re.search(r"<svg[^>]*>(.*)</svg>", svg, re.S).group(1)
    inner = re.sub(r"\s+", " ", inner).strip()
    inner = inner.replace(" />", "/>")
    symbols.append(f'<symbol id="i-{name[:-4]}" viewBox="0 0 24 24">{inner}</symbol>')

sprite = "".join(symbols)
js = f"""// Lucide icon sprite (https://lucide.dev, ISC). This file is generated by
// src/icons/make-sprite.py from src/icons/*.svg, do not edit by hand.
App.icons = (() => {{
  const SPRITE = '{sprite}';

  // Inserts the sprite into the document once, afterwards icons are taken via <use>.
  function install() {{
    if (document.getElementById('icon-sprite')) return;
    const holder = document.createElement('div');
    holder.innerHTML = '<svg id="icon-sprite" xmlns="http://www.w3.org/2000/svg" style="display:none">' + SPRITE + '</svg>';
    document.body.prepend(holder.firstChild);
  }}

  // svg('sun') -> <svg class="icon"><use href="#i-sun"/></svg>
  function svg(name, className) {{
    const el = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
    el.setAttribute('class', 'icon' + (className ? ' ' + className : ''));
    el.setAttribute('aria-hidden', 'true');
    const use = document.createElementNS('http://www.w3.org/2000/svg', 'use');
    use.setAttribute('href', '#i-' + name);
    el.append(use);
    return el;
  }}

  return {{ install, svg, names: {sorted(n[:-4] for n in os.listdir(HERE) if n.endswith('.svg'))!r} }};
}})();
"""
with open(OUT, "w", encoding="utf-8") as f:
    f.write(js)
print("wrote", os.path.relpath(OUT, os.getcwd()), len(symbols), "icons")
